neo4j:
  image: neo4j:3.0
  environment:
    NEO4J_AUTH: none
  ports:
    - '7474:7474'
    - '7687:7687'
  volumes:
    - ./neo4j/data:/data

app:
  build: .
  links:
    - neo4j
  volumes:
    - .:/app